version: '3.8'
services:
  my-app: 
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=db_password2024
      - DB_NAME=nzela_hub_api
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - app-network
  db: 
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=db_password2024
      - MARIADB_ROOT_USER=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql #Pour la persistence de données
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  
  adminer: 
    image: adminer
    restart: always
    ports:
      - "8080:8080"  
    networks:
      - app-network
volumes:
    db_data:

networks:
  app-network:
    driver: bridge