name: Continuous deployment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull docker image
        run: sudo docker pull hobed24/nzela-hub-api:0.0.1

      - name: Delete old docker container
        run: sudo docker rm -f nzela-hub-api-container || true 

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name nzela-hub-api-container hobed24/nzela-hub-api:0.0.1
