name: Continous deployment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

permissions:
  contents: read

jobs:

  build: 
    runs-on: self-hosted

    steps:
    - name: Pull docker image
    - run: sudo docker pull hobed24/nzela-hup-api:0.0.1
    
    - name: Delete old docker image
    - run: sudo docker rm -f nzela-hup-api-container || true 

    - name: Run Docker Container
    - run: sudo docker run -d -p 8080:8080 --name nzela-hup-api-container hobed24/nzela-hup-api
       
    #     env: 
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PWD }}
    #     run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    # - name: Build Docker Image
    #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nzela-hup-api:0.0.1 .

    # - name: Push to Docker Hub 
    #   run: docker push ${{ secrets.DOCKER_USERNAME }}/nzela-hup-api:0.0.1
      