name: EKS Continuous deployment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Remplacez par votre région AWS

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name nzela-hub-api-cluster --region us-east-2

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/configmap.yaml
          kubectl apply -f ./k8s/db.yaml
          kubectl apply -f ./k8s/adminer.yaml
          kubectl apply -f ./k8s/my-app.yaml
